spring:
  application:
    name: SAAS_HRM
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.115.13.221:3306/ihrm?useSSL=true&characterEncoding=utf8&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8989
  servlet:
    context-path: /ihrm